[package]
name = "monad-triedb-utils"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-eth-types = { path = "../monad-eth-types" }
monad-state-backend = { path = "../monad-state-backend" }
monad-triedb = { path = "../monad-triedb" }
monad-types = { path = "../monad-types" }

alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
monad-eth-testutil = { path = "../monad-eth-testutil" }

clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
