[package]
name = "monad-eth-types"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["serde"] }
reth-primitives = { workspace = true }
serde = { workspace = true }
